# -*- coding: utf-8 -*-
"""파일명 변경.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19foC1CgrXqjeTBLTC4A6_5S2rYPbvGXI
"""

import os
file_path = "C:\\MyPaperWork_YH\\src\\matlab_converter\\20230620_KT\\20230620_data\\20230620_data\\2306_backlay_yr\\2306_backlay_yr"
file_names = os.listdir(file_path)

i = 1
for name in file_names:
    src = os.path.join(file_path, name)
    dst = "backlay" + str(i)
    dst = os.path.join(file_path, dst)
    os.rename(src, dst)
    i += 1

l = [0] * 3
print(l)
import numpy as np
print(np.shape(l))